import React, { useState } from 'react';
import { Building2, Shield, User as UserIcon, Lock, Database, Mail, Briefcase } from 'lucide-react';
import type { Business, User } from '../../../shared/types';
import { UserRole, UserStatus } from '../../auth/types';

interface SettingsViewProps {
    currentUser: User;
    businesses: Business[];
    handleAddBusiness: (business: Omit<Business, 'id'>) => void;
    allUsers: User[];
    setAllUsers: (user: User) => void; // This is now updateUser
}

const ROLE_PERMISSION_MAP: Record<UserRole, number> = {
    [UserRole.SUPER_ADMIN]: 1,
    [UserRole.ADMIN]: 2,
    [UserRole.FINANCE]: 3,
    [UserRole.PURCHASING_OFFICER]: 4,
    [UserRole.CIC]: 5,
    [UserRole.MANAGER]: 6,
    [UserRole.EMPLOYEE]: 7,
    [UserRole.AUDITOR]: 8
};

export const SettingsView: React.FC<SettingsViewProps> = ({ currentUser, businesses, handleAddBusiness, allUsers, setAllUsers: updateUser }) => {
    const [newBiz, setNewBiz] = useState({ name: '', tin: '', address: '', currency: 'PHP' });
    const [newUser, setNewUser] = useState<Partial<User>>({ name: '', email: '', role: UserRole.EMPLOYEE, businessId: businesses[0]?.id || '' });
    const [editingUserId, setEditingUserId] = useState<string | null>(null);
    
    const [passwords, setPasswords] = useState({ current: '', new: '', confirm: '' });

    const isStaging = import.meta.env.MODE === 'staging';

    const handleCreateOrUpdateUser = () => {
        if (newUser.name && newUser.email && newUser.role && newUser.businessId) {
            const userToSave: User = {
                id: editingUserId || ``, // ID will be generated by Firestore
                avatar: newUser.avatar || '',
                department: newUser.department || 'General',
                name: newUser.name,
                email: newUser.email,
                role: newUser.role,
                businessId: newUser.businessId,
                status: newUser.status || UserStatus.ACTIVE,
            };
            if(editingUserId) {
                updateUser(userToSave);
            }
            alert(editingUserId ? "User Updated" : "Create User functionality not implemented in this view");
            resetUserForm();
        }
    };

    const handleEditUserClick = (user: User) => {
        setNewUser(user);
        setEditingUserId(user.id);
    };

    const resetUserForm = () => {
        setNewUser({ name: '', email: '', role: UserRole.EMPLOYEE, businessId: businesses[0]?.id || '' });
        setEditingUserId(null);
    };

    const handleChangePassword = () => {
        if (passwords.new !== passwords.confirm) {
            alert("New passwords do not match.");
            return;
        }
        alert("Password change functionality not implemented in demo.");
        setPasswords({ current: '', new: '', confirm: '' });
    };

    const cardClass = "bg-slate-800/50 backdrop-blur-xl p-6 rounded-xl shadow-lg border border-slate-700";
    const inputClass = "w-full p-2 bg-slate-900/50 border border-slate-600 rounded-lg text-white focus:ring-2 focus:ring-purple-500 focus:outline-none placeholder-slate-500";
    const labelClass = "block text-sm font-medium text-slate-300 mb-1";

    return (
        <div className="space-y-8 max-w-4xl animate-in fade-in slide-in-from-bottom-4 pb-10 text-white">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold text-white">System Settings</h1>
                    <p className="text-slate-400 text-sm">Manage your account and system preferences.</p>
                </div>
                {isStaging && (
                    <div className="px-3 py-1 bg-yellow-900/30 text-yellow-200 rounded-full text-xs font-bold border border-yellow-500/30 flex items-center gap-1">
                        <Database size={12} /> STAGING DATABASE
                    </div>
                )}
            </div>

            {/* My Profile Section */}
            <div className={cardClass}>
                <h3 className="font-bold text-lg flex items-center gap-2 text-white mb-6"><UserIcon size={20} className="text-purple-400" /> My Profile</h3>
                <div className="flex items-start gap-6">
                    <div className="w-24 h-24 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center text-3xl font-bold text-white shadow-lg border-2 border-slate-700">
                        {currentUser.name.charAt(0)}
                    </div>
                    <div className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label className="block text-xs font-semibold text-slate-400 uppercase mb-1">Full Name</label>
                            <div className="text-white font-medium text-lg">{currentUser.name}</div>
                        </div>
                        <div>
                            <label className="block text-xs font-semibold text-slate-400 uppercase mb-1">Role</label>
                            <div className="flex items-center gap-2">
                                <Briefcase size={16} className="text-slate-500" />
                                <span className="text-slate-200 font-medium">{currentUser.role.replace(/_/g, ' ')}</span>
                            </div>
                        </div>
                        <div>
                            <label className="block text-xs font-semibold text-slate-400 uppercase mb-1">Email Address</label>
                            <div className="flex items-center gap-2">
                                <Mail size={16} className="text-slate-500" />
                                <span className="text-slate-200 font-medium">{currentUser.email}</span>
                            </div>
                        </div>
                        <div>
                            <label className="block text-xs font-semibold text-slate-400 uppercase mb-1">Business Unit</label>
                            <div className="flex items-center gap-2">
                                <Building2 size={16} className="text-slate-500" />
                                <span className="text-slate-200 font-medium">{businesses.find(b => b.id === currentUser.businessId)?.name || 'N/A'}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Security Section */}
            <div className={cardClass}>
                <h3 className="font-bold text-lg mb-6 flex items-center gap-2 text-white"><Lock size={20} className="text-purple-400" /> Security</h3>
                <div className="max-w-md space-y-4">
                    <div>
                        <label className={labelClass}>Current Password</label>
                        <input 
                            type="password" 
                            className={inputClass} 
                            value={passwords.current}
                            onChange={e => setPasswords({...passwords, current: e.target.value})}
                        />
                    </div>
                    <div>
                        <label className={labelClass}>New Password</label>
                        <input 
                            type="password" 
                            className={inputClass} 
                            value={passwords.new}
                            onChange={e => setPasswords({...passwords, new: e.target.value})}
                        />
                    </div>
                    <div>
                        <label className={labelClass}>Confirm New Password</label>
                        <input 
                            type="password" 
                            className={inputClass} 
                            value={passwords.confirm}
                            onChange={e => setPasswords({...passwords, confirm: e.target.value})}
                        />
                    </div>
                    <button 
                        onClick={handleChangePassword}
                        disabled={!passwords.current || !passwords.new || !passwords.confirm}
                        className="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-medium"
                    >
                        Update Password
                    </button>
                </div>
            </div>

            {currentUser.role === UserRole.SUPER_ADMIN && (
                <>
                    {/* Business Unit Management */}
                    <div className={cardClass}>
                        <h3 className="font-bold text-lg mb-6 flex items-center gap-2 text-white"><Building2 size={20} className="text-purple-400" /> Business Unit Management</h3>
                        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                            <input className={inputClass} placeholder="Business Name" value={newBiz.name} onChange={e => setNewBiz({ ...newBiz, name: e.target.value })} />
                            <input className={inputClass} placeholder="TIN" value={newBiz.tin} onChange={e => setNewBiz({ ...newBiz, tin: e.target.value })} />
                            <input className={inputClass} placeholder="Address" value={newBiz.address} onChange={e => setNewBiz({ ...newBiz, address: e.target.value })} />
                            <button onClick={() => { handleAddBusiness(newBiz); setNewBiz({ name: '', tin: '', address: '', currency: 'PHP' }); }} className="bg-purple-600 text-white py-2 rounded-lg hover:bg-purple-700 font-medium transition-colors">Add Business</button>
                        </div>
                        <div className="space-y-2 max-h-60 overflow-y-auto custom-scrollbar">
                            {businesses.map(b => (
                                <div key={b.id} className="p-3 border border-slate-700 rounded-lg bg-slate-900/30 text-sm flex justify-between items-center hover:bg-slate-800/50 transition-colors">
                                    <span className="font-medium text-slate-200">{b.name}</span>
                                    <span className="text-slate-500 font-mono text-xs">{b.tin}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* User Management */}
                    <div className={cardClass}>
                        <h3 className="font-bold text-lg mb-6 flex items-center gap-2 text-white"><Shield size={20} className="text-red-400" /> User Management</h3>
                        {/* Create/Edit Form */}
                        <div className="bg-slate-900/30 p-4 rounded-lg border border-slate-700 mb-6">
                            <h4 className="text-sm font-bold text-slate-300 mb-3">{editingUserId ? 'Edit User' : 'Create New User'}</h4>
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 items-end">
                                <div>
                                    <label className="block text-xs font-medium text-slate-400 mb-1">Name</label>
                                    <input className={inputClass} placeholder="Full Name" value={newUser.name} onChange={e => setNewUser({ ...newUser, name: e.target.value })} />
                                </div>
                                <div>
                                    <label className="block text-xs font-medium text-slate-400 mb-1">Email</label>
                                    <input className={inputClass} placeholder="email@example.com" value={newUser.email} onChange={e => setNewUser({ ...newUser, email: e.target.value })} />
                                </div>
                                <div>
                                    <label className="block text-xs font-medium text-slate-400 mb-1">Role</label>
                                    <select className={inputClass} value={newUser.role} onChange={e => setNewUser({ ...newUser, role: e.target.value as UserRole })}>
                                        {Object.keys(ROLE_PERMISSION_MAP).map(role => (
                                            <option key={role} value={role} className="bg-slate-800 text-white">{role.replace('_', ' ')}</option>
                                        ))}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-xs font-medium text-slate-400 mb-1">Business Unit</label>
                                    <select className={inputClass} value={newUser.businessId} onChange={e => setNewUser({ ...newUser, businessId: e.target.value })}>
                                        {businesses.map(b => (
                                            <option key={b.id} value={b.id} className="bg-slate-800 text-white">{b.name}</option>
                                        ))}
                                    </select>
                                </div>
                            </div>
                            <div className="mt-4 flex justify-end gap-2">
                                {editingUserId && <button onClick={resetUserForm} className="text-slate-400 text-sm px-4 py-2 hover:text-white hover:bg-slate-800 rounded-lg transition-colors">Cancel</button>}
                                <button onClick={handleCreateOrUpdateUser} className="bg-purple-600 text-white py-2 px-6 rounded-lg text-sm hover:bg-purple-700 font-medium transition-colors">
                                    {editingUserId ? 'Update User' : 'Create User'}
                                </button>
                            </div>
                        </div>

                        {/* User List Table */}
                        <div className="overflow-x-auto border border-slate-700 rounded-lg">
                            <table className="w-full text-left text-sm">
                                <thead className="bg-slate-900/50 text-xs uppercase text-slate-400 border-b border-slate-700">
                                    <tr>
                                        <th className="px-4 py-3">Name</th>
                                        <th className="px-4 py-3">Email</th>
                                        <th className="px-4 py-3">Role</th>
                                        <th className="px-4 py-3">Business Unit</th>
                                        <th className="px-4 py-3 text-right">Action</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-700/50">
                                    {allUsers.map(user => (
                                        <tr key={user.id} className="hover:bg-slate-800/50 transition-colors">
                                            <td className="px-4 py-3 font-medium text-slate-200">{user.name}</td>
                                            <td className="px-4 py-3 text-slate-400">{user.email}</td>
                                            <td className="px-4 py-3">
                                                <span className="px-2 py-1 bg-slate-700/50 border border-slate-600/50 rounded-md text-xs font-medium text-slate-300">
                                                    {user.role.replace('_', ' ')}
                                                </span>
                                            </td>
                                            <td className="px-4 py-3 text-slate-500">
                                                {businesses.find(b => b.id === user.businessId)?.name || '-'}
                                            </td>
                                            <td className="px-4 py-3 text-right">
                                                <button onClick={() => handleEditUserClick(user)} className="text-cyan-400 hover:text-cyan-300 font-medium text-xs hover:underline">
                                                    Edit
                                                </button>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </>
            )}
        </div>
    );
};